ONG/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views
from campagne import views as campagne_views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', campagne_views.campagne_list,name='home'),
    re_path(r'^about/$', views.about),
    re_path(r'^accounts/',include("accounts.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r'^campagne/', include('campagne.urls')),
]
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$',views.signup_view, name = "signup"),
    re_path(r'^login/$',views.login_view, name = "login"),
    re_path(r'^logout/$',views.logout_view, name = "logout")
]

campagne/urls.py
from django.urls import path, re_path
from . import views

app_name = 'campagne'

urlpatterns = [
    re_path(r'^$',views.campagne_list, name="campagne_list"),
    re_path(r'^create/$',views.article_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.campagne_detail, name="detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

campagne/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Campagne(models.Model):
    charity_number = models.CharField(max_length=50)
    slug = models.SlugField()
    nom = models.CharField(max_length=100)
    histoire = models.TextField()
    montant = models.DecimalField(max_digits=6, decimal_places=2, default=0.0)
    supporteurs = models.IntegerField(max_length=100, null = True)
    thumbnail = models.ImageField(default='default.png', blank=True)
    fundraiser = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.nom
    
    def snippet(self):
        return self.histoire[:50] + '...'

campagne/forms.py
from django import forms
from . import models

class CreateCampagne(forms.ModelForm):
    class Meta:
        model = models.Campagne
        fields = ['charity_number','slug', 'nom',  'histoire', 'thumbnail',]

ONG/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@csrf_exempt
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            #log user in
            return redirect('campagne:campagne_list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('campagne:campagne_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form' : form})

@csrf_exempt
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('campagne:campagne_list')

campagne/views.py
from django.shortcuts import render,redirect
from .models import Campagne
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def campagne_list(request):
    campagnes = Campagne.objects.all()
    return render(request, 'campagne/campagne_list.html' , {'campagne' : campagnes})

def campagne_detail(request, slug):
    # return HttpResponse(slug)
    campagne = Campagne.objects.get(slug=slug)
    return render(request, 'campagne/campagne_detail.html', { 'campagne': campagne })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateCampagne(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.fundraiser = request.user
            instance.save()
            return redirect('campagne:campagne_list')
    else:
        form = forms.CreateCampagne()
    return render(request,'campagne/campagne_create.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Log In">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Sign Up">
    </form>
{% endblock %}

campagne/templates/campagne/campagne_create.html
{% extends 'base.html' %}


{% block content %}
    <div class="create-campagne">
        <h2>Create an Awesome New Campagne</h2>
        <br>
        <form class="site-form" action="{% url 'campagne:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

campagne/templates/campagne/campagne_detail.html
{% extends 'base.html'%}

{% block content %}
<div class="campagne-detail">
    <div class="campagne">
        <img src="{{ campagne.thumbnail.url}}">
        <h2>{{ campagne.nom }}</h2>
        <p>{{ campagne.charity_number }}</p>
        <p>{{ campagne.histoire }}</p>
        <p>{{ campagne.montant }}</p>
        <p>{{ campagne.supporteurs }}</p>
        <form method="POST">
            <button type="submit" class="donate"><a href="https://buy.stripe.com/test_14k5nv89M03xamAcMM">Donate</a></button>
        </form>
    </div>
</div>
{% endblock %}

campagne/templates/campagne/campagne_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Liste de Campagnes</h1>
    <div class="campagnes">
        {% for campagne in campagne %}
            <div class="campagne">
                <h2><a href="{% url 'campagne:detail' slug=campagne.slug %}">{{ campagne.nom }}</a></h2>
                <p>{{ campagne.charity_number }}</p>
                <p>{{ campagne.snippet }}</p>
                <p class="fundraiser">Created by {{ campagne.fundraiser.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About Us</h1>
        <p>We like django.</p>
    </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ONG</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.svg' %}" alt="Charity compass" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn" type="submit">Log Out</button>
                        </form>
                    </li>
                    <li><a href="{% url 'campagne:create' %}" class="highlight">New Campagne</a></li>
                    {% else %}
                        <li><a class="btn" href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a class="btn" href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% if user.is_authenticated %}
                <h3 style="text-align: center; color: #00dba0;">Bienvenue, {{user.username}}</h3>
            {% endif %}
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Make some donations!!</p>
    </body>
</html>